# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eadef7600e9a6e660b6ec55ee98f16568c817eb30d40ee03faed916889aa9984fbc1ec13ab6942d954e29b5dfe6236094eed94d05c0ff2ec5ee3d289efc53800

test:
  secret_key_base: 05187493f0d59bd9ad7d7fc939f2eec2edc0351d5a8bcfa2456bb910bbc7e0e05cb9617d4d7f5ed16192e6989098d5a56340a48b4644e1013afbebdb89cf2f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
