Book.create code: "TA31", name: "Tiếng Anh 3 Tập 1 SGK", description: "English 3 (part 1) for student"
Book.create code: "TA32", name: "Tiếng Anh 3 Tập 2 SGK", description: "English 3 (part 1) for student"
Book.create code: "BT3", name: "Tiếng Anh 3 SBT", description: "Exercises English 3 for student"
Book.create code: "TA41", name: "Tiếng Anh 4 Tập 1 SGK", description: "English 4 (part 1) for student"
Book.create code: "TA42", name: "Tiếng Anh 4 Tập 2 SGK", description: "English 4 (part 2) for student"
Book.create code: "BT4", name: "Tiếng Anh 4 SBT", description: "Exercises English 4 for student"
Book.create code: "TA51", name: "Tiếng Anh 5 Tập 1 SGK", description: "English 5 (part 1) for student"
Book.create code: "TA52", name: "Tiếng Anh 5 Tập 2 SGK", description: "English 5 (part 2) for student"
Book.create code: "BT5", name: "Tiếng Anh 5 SBT", description: "Exercises English 5 for student"
